[package]
name = "dangerzone-container"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
infer = "0.5.0"

[[bin]]
name = "dangerzone-container"
path = "src/main.rs"
